---
spec/spec_helper_acceptance.rb:
  windows: true
  dependencies:
    - puppetlabs-stdlib
    - opentable-altlib
    - herculesteam/augeasproviders
spec/acceptance/nodesets/windows-2008R2-serverstandard-x64.yml:
  unmanaged: true
